# Dataset and general parameters
device: "cpu"
dataset: "faces"
batch_size: 16
debug: False

# Noise Scheduler parameters
noise: "linear" 
timesteps: 300
start: 0.001
end: 0.500

# Model shape
shape:
  - [64, 128, 256, 512, 1024]
  - [1024, 512, 256, 128, 64]

# Training parameterss
lr: 0.001
epochs: 10